url_link = ["google.com", "youtube.com", "amazon.com", "facebook.com",
            "yahoo.com", "reddit.com", "wikipedia.org", "ebay.com",
            "bing.com", "netflix.com", "office.com", "shopify", "twitch.com",
            "cnn.com", "linkedlin.com", "instagram.com", "twitter.com",
            "baidu.com", "microsoft.com", "live.com", "apple.com", "reddit.com",
            "dhl.com", "blogger.com", "mozilla.org", "cloudflare.com", "adobe.com",
            "whatsapp.com", "blogspot.com", "europa.eu", "github.com", "vimeo.com",
            "vk.com", "uol.com", "tiktok.com", "wikimedia.org", "msn.com", ".gov",
            "w3.org", "opera.com", "weebly.com", "buydomains.com", "wordpress.com",
            "medium.com", "dailymotion.com", "feedburner.com", "bbc.co", "globo.com",
            "jimdofree.com", "imdb.com", "nytimes.com", "gstatic.com", "slideshare.net",
            "dropbox.com", "paypal.com", "gravatar.com", "line.me", "netvibes.com",
            "forbes.com", "who", "soundcloud.com", "namecheap.com", "dan.com", "estadao.com",
            "hugedomains.com", "mirror.co", "scribd.com", "usatoday.com", "issuu.com",
            "wp.com", "nature.com", "4shared.com", "foxnews.com", "independent.co",
            "tinyurl.com", "samsung.com", "alienpress.com", "telegram.me", "indiatimes.com",
            "huffpost.com", "myspace.com", "reuters.com", "booking.com", "archive.org",
            "mediafire.com", "washingtonpost.com", "cnet.com", "cbsnews.com", "dailymail.co",
            "thesun.co", "mail", "fandom.com", "pinterest.com", "bit.ly", "zoom", "huawei.com",
            "yandex.com", "steampowered.com", "nginx.org", "hp.com", "jobstreet.com", "statista.com",
            "espn.com", "playstation.com", "walmart.com", "android.com", "clickbank.net"]